"""drop orphaned CV-generation columns from applications

Revision ID: 4e9f0a320779
Revises: c073e73561c1
Create Date: 2026-08-20 11:51:52.043524+00:00

`pdf_path`/`tailored_cv_json` predate this project's Alembic setup: they were
part of the earlier server-side PDF-rendering approach and were dropped from
the `Application` model without ever going through a migration (there wasn't
one yet). Only the hand-patched, already-running production database still
has them - the baseline migration (`c073e73561c1`, autogenerated from the
*current* models) never included them, so a from-scratch database (a fresh
install, or this project's own SQLite test fixtures) never has these columns
to begin with. `upgrade()` checks column existence first so this migration is
a no-op there and only takes effect against the one already-running database
that still carries the leftover columns.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4e9f0a320779'
down_revision: str | None = 'c073e73561c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    existing_columns = {col["name"] for col in sa.inspect(bind).get_columns("applications")}
    if "pdf_path" in existing_columns:
        op.drop_column('applications', 'pdf_path')
    if "tailored_cv_json" in existing_columns:
        op.drop_column('applications', 'tailored_cv_json')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('tailored_cv_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('applications', sa.Column('pdf_path', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
